CREATE TABLE Players (
 PID INTEGER,
 PlayerName CHAR(40) NOT NULL,
 DOB DATE,
 POSITION CHAR(8),
 PRIMARY KEY (PID));
 
CREATE TABLE Seasons (
 SeasonYear INTEGER,
 PRIMARY KEY (SeasonYear));
 
CREATE TABLE Teams (
 TID INTEGER,
 PRIMARY KEY (TID));

 
CREATE TABLE Games (
 GameID INTEGER,
 GameDate DATE,
 Home…TID INTEGER NOT NULL,
 Away…TID INTEGER NOT NULL,
 SeasonYear INTEGER NOT NULL,
 PRIMARY KEY (GameID),
 FOREIGN KEY (SeasonYear) REFERENCES Seasons (SeasonYear),
 FOREIGN KEY (Home…TID) REFERENCES Teams(TID),
 FOREIGN KEY (Away…TID) REFERENCES Teams(TID));
 
CREATE TABLE IndPerf (
 GameID INTEGER,
 PID INTEGER,
 TID INTEGER NOT NULL,
 FGM INTEGER NOT NULL,
 FGA INTEGER NOT NULL,
 TPM INTEGER NOT NULL,
 TPA INTEGER NOT NULL,
 FTM INTEGER NOT NULL,
 FTA INTEGER NOT NULL,
 Reb INTEGER NOT NULL,
 Ast INTEGER NOT NULL,
 Stl INTEGER NOT NULL,
 Blk INTEGER NOT NULL,
 Turnovers INTEGER NOT NULL,
 PF INTEGER NOT NULL,
 Pts INTEGER NOT NULL,
 PRIMARY KEY (GameID, PID),
 FOREIGN KEY (GameID) REFERENCES Games (GameID),
 FOREIGN KEY (PID) REFERENCES Players (PID),
 FOREIGN KEY (TID) REFERENCES Teams (TID));
 
CREATE TABLE DidNotPlay (
 PID INTEGER,
 SeasonYear INTEGER NOT NULL,
 Count INTEGER NOT NULL,
 PRIMARY KEY (PID, SeasonYear),
 FOREIGN KEY (PID) REFERENCES Players (PID),
 FOREIGN KEY (SeasonYear) REFERENCES Seasons (SeasonYear));
 
CREATE TABLE BelongsTo (
 TID INTEGER,
 SeasonYear INTEGER NOT NULL,
 TeamName CHAR(40) NOT NULL,
 TeamAbbr CHAR(3) NOT NULL,
 PRIMARY KEY (TID, SeasonYear),
 FOREIGN KEY (TID) REFERENCES Teams (TID),
 FOREIGN KEY (SeasonYear) REFERENCES Seasons (SeasonYear));
 
CREATE TABLE Ejections (
 PID INTEGER,
 SeasonYear INTEGER NOT NULL,
 Count INTEGER NOT NULL,
 PRIMARY KEY (PID, SeasonYear),
 FOREIGN KEY (PID) REFERENCES Players (PID),
 FOREIGN KEY (SeasonYear) REFERENCES Seasons (SeasonYear));
 
CREATE TABLE FlagrantFouls (
 PID INTEGER,
 SeasonYear INTEGER NOT NULL,
 Count INTEGER NOT NULL,
 PRIMARY KEY (PID, SeasonYear),
 FOREIGN KEY (PID) REFERENCES Players (PID),
 FOREIGN KEY (SeasonYear) REFERENCES Seasons (SeasonYear));
